config/routes.rb
Rails.application.routes.draw do
  resources :organisations, only: %i[show update]
  resources :records
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "organisations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/organisation.rb
class Organisation < ApplicationRecord
  SOURCE_URL = "https://raw.githubusercontent.com/github/government.github.com/gh-pages/_data/governments.yml".freeze
  GOV_UK_GROUP = "U.K. Central".freeze
  GITHUB_KEY = Rails.configuration.github_key

  scope :gov_uk, -> { where(group: GOV_UK_GROUP) }
  has_many :records

  def self.populate
    response = Faraday.get(SOURCE_URL)
    raise "Populate failed: #{response.body}" unless response.success?

    data = YAML.load(response.body)

    data.collect { |group, repos|
      repos.collect { |name| find_or_create_by group:, name: }
    }.flatten
  end

  def find_and_create_records
    client = Octokit::Client.new(access_token: Organisation::GITHUB_KEY)
    data = client.get("/search/code?per_page=50&q=openapi\:+extension:yaml+org:#{name}")
    data[:items].collect do |item|
      url = item[:html_url]
      url.gsub!(/^https:\/\/github\.com/, "https://raw.githubusercontent.com")
      url.gsub!(/\/blob\//, "/")
      records.find_or_create_by!(url:)
    end
  end
end

app/models/process_report.rb
class ProcessReport < ApplicationRecord
  belongs_to :record
end

app/models/record.rb
class Record < ApplicationRecord
  scope :with_metadata, -> { where.not("coalesce(metadata ->> 'title') = ''") }

  has_many :process_reports, dependent: :delete_all
  belongs_to :organisation, optional: true

  validates :url, presence: true

  def process
    return unless valid?

    GetUrlContent.call(self)
    reload
    GenerateMetadata.call(self) if specification.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  # GET /organisations
  def index
    @organisations = Organisation.gov_uk
  end

  # GET /organisations/1
  def show
    organisation
  end

  # PATCH/PUT /organisations/1
  def update
    records = organisation.find_and_create_records
    records.each(&:process) if records.present?
    redirect_to @organisation, notice: "Organisation records update initiated."
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def organisation
    @organisation ||= Organisation.find(params.expect(:id))
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  after_action :process_record, only: %i[create update]
  # GET /records
  def index
    @records = Record.all
  end

  # GET /records/1
  def show
    record
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
    record
  end

  # POST /records
  def create
    @record = Record.new(record_params)

    if record.save
      redirect_to record, notice: "Record was successfully created."
    else
      render :new, status: :unprocessable_content
    end
  end

  # PATCH/PUT /records/1
  def update
    record.process
    redirect_to record, notice: "Record was successfully updated.", status: :see_other
  end

  # DELETE /records/1
  def destroy
    record.destroy!
    redirect_to records_path, notice: "Record was successfully destroyed.", status: :see_other
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def record
    @record ||= Record.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def record_params
    params.expect(record: %i[url])
  end

  def process_record
    record.process
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def url_or_title(record)
    return record.url if record.metadata.blank? || record.metadata["title"].blank?

    record.metadata["title"]
  end

  def render_markdown(text)
    return if text.blank?

    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, tables: true)
    markdown.render(text).html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="govuk-template govuk-template--rebranded">
  <head>
    <% service_name = "Metadata from API Spec" %>
    <title><%= [service_name, content_for(:title)].compact.join(" - ") %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, defer: true %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <script>document.body.className = ((document.body.className) ? document.body.className + ' js-enabled' : 'js-enabled');</script>
    <%=
      govuk_header(service_name:) do |header|
        header.with_navigation_item(
          text: 'Organisations',
          href: root_path,
          active: current_page?(root_path)
        )

        header.with_navigation_item(
          text: 'Records',
          href: records_path,
          active: current_page?(records_path)
        )
      end
    %>

    <div class="govuk-width-container ">
      <main class="govuk-main-wrapper " id="main-content" role="main">
        <div class="govuk-grid-row">
          <div class="govuk-grid-column-three-quarters">
            &nbsp;
            <%= govuk_notification_banner(title_text: 'Notice', text: notice, success: true) if notice.present? %>
            <%= govuk_notification_banner(title_text: 'Alert', text: alert) if alert.present? %>
          </div>
          <div class="govuk-grid-column-one-quarter govuk-!-text-align-right">
            <%#= user_signed_in? ? logout_button : login_button %>
          </div>
        </div>
        <div class="govuk-grid-row">
          <div class="govuk-grid-column-full">
            <%= yield %>
          </div>
        </div>
      </main>
    </div>
    <%= render GovukComponent::FooterComponent.new do |footer| %>
      <%= footer.with_meta_html %>
    <% end %>
  </body>
</html>

app/views/organisations/index.html.erb
<% content_for :title, "Organisations" %>

<h1>Organisations</h1>

<div id="organisations">
  <%=
    govuk_table do |table|
      table.with_head do |head|
        head.with_row do |row|
          row.with_cell(
            text: 'Name'
          )

          row.with_cell()
        end
      end

      table.with_body do |body|
        @organisations.each do |organisation|
          body.with_row do |row|
            row.with_cell(
              text: organisation.name
            )

            row.with_cell(
              text: link_to("View organisation's records", organisation, class: "govuk-link")
            )
          end
        end
      end
    end
  %>
</div>

app/views/organisations/new.html.erb
<% content_for :title, "New organisation" %>

<h1>New organisation</h1>

<%= render "form", organisation: @organisation %>

<br>

<div>
  <%= link_to "Back to organisations", organisations_path %>
</div>

app/views/organisations/show.html.erb
<%= content_for :title, "#{@organisation.name} records" %>

<h1><%= @organisation.name %></h1>

<h2>Records</h2>

<%= render "records/records", records: @organisation.records.with_metadata %>

<%= button_to 'Update records', @organisation, method: :patch %>

app/views/records/_form.html.erb
<%= form_with(model: record) do |form| %>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/records/_records.html.erb
<div id="records">
  <% if records.present? %>
    <%=
      govuk_table do |table|
        table.with_head do |head|
          head.with_row do |row|
            row.with_cell(
              text: 'URL'
            )

            row.with_cell()
          end
        end

        table.with_body do |body|
          records.each do |record|
            body.with_row do |row|
              row.with_cell(
                text: url_or_title(record),
                html_attributes: { class: 'record-link' }
              )

              row.with_cell(
                text: link_to("View record", record, class: "govuk-link")
              )
            end
          end
        end
      end
    %>
  <% else %>
    <p>No records found</p>
  <% end %>
</div>

app/views/records/edit.html.erb
<% content_for :title, "Editing record" %>

<h1>Editing record</h1>

<%= render "form", record: @record %>

<br>

<div>
  <%= link_to "Show this record", @record %> |
  <%= link_to "Back to records", records_path %>
</div>

app/views/records/index.html.erb
<% content_for :title, "Records" %>

<h1>Records</h1>

<%= render "records", records: @records %>

<%= link_to "New record", new_record_path %>

app/views/records/new.html.erb
<% content_for :title, "New record" %>

<h1>New record</h1>

<%= render "form", record: @record %>

<br>

<div>
  <%= link_to "Back to records", records_path %>
</div>

app/views/records/show.html.erb
<% if @record.metadata.present? && @record.metadata["title"].present? %>
  <% if @record.metadata["type"] =~ /^openapi/ %>
    <div id="api-spec" data-url="<%= @record.url %>"></div>
  <% else %>
    <h2><%= @record.metadata["title"] %></h2>
    <p><%= render_markdown(@record.metadata["description"]) %></p>
  <% end %>
<% else %>
  <h2>URL</h2>
  <p><%= @record.url %></p>
<% end %>

<%= link_to "Back to organisation's records", organisation_path(@record.organisation) %>

<h3>Metadata</h3>
<pre>
<%= JSON.pretty_generate(@record.metadata) if @record.metadata.present? %>
</pre>

<h3>Specification</h3>
<pre>
<%= @record.specification %>
</pre>

  <%= button_to "Update Record", @record, method: :patch %>

</div>